// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2N7K_OyaQAHzo_Fx05JnrwqNJOsLIVHI',
    appId: '1:634223971849:web:2a950aac03a9324f87f2d8',
    messagingSenderId: '634223971849',
    projectId: 'evarancorp-recipes-book',
    authDomain: 'evarancorp-recipes-book.firebaseapp.com',
    databaseURL: 'https://evarancorp-recipes-book-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'evarancorp-recipes-book.appspot.com',
    measurementId: 'G-HBRK0DC1WM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdDAo9LHaLptL46RfGJavAvVkO2ZPOlqw',
    appId: '1:634223971849:android:1c588479a8e3013087f2d8',
    messagingSenderId: '634223971849',
    projectId: 'evarancorp-recipes-book',
    databaseURL: 'https://evarancorp-recipes-book-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'evarancorp-recipes-book.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEPpzNOPV5IUuC_YEbejC7Pm6kN-teowY',
    appId: '1:634223971849:ios:5880e7d88ab550c687f2d8',
    messagingSenderId: '634223971849',
    projectId: 'evarancorp-recipes-book',
    databaseURL: 'https://evarancorp-recipes-book-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'evarancorp-recipes-book.appspot.com',
    iosClientId: '634223971849-bbpb5j61j6oqls5ceui5329o29qv2vrr.apps.googleusercontent.com',
    iosBundleId: 'com.evaranshark.recipesBookV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2N7K_OyaQAHzo_Fx05JnrwqNJOsLIVHI',
    appId: '1:634223971849:web:e38546bbd4df0f7287f2d8',
    messagingSenderId: '634223971849',
    projectId: 'evarancorp-recipes-book',
    authDomain: 'evarancorp-recipes-book.firebaseapp.com',
    databaseURL: 'https://evarancorp-recipes-book-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'evarancorp-recipes-book.appspot.com',
    measurementId: 'G-Y78XDL373E',
  );
}
